pipeline {
	agent any
	environment {
        AWS_ACCES_KEY = credentials('AWS_ACCES_KEY')
		AWS_PRIVATE_KEY = credentials('AWS_PRIVATE_KEY')
   	}
	stages {

		stage('Create kubernetes cluster') {
			steps {
				sh '''
					export AWS_ACCESS_KEY_ID=$AWS_ACCES_KEY
					export AWS_SECRET_ACCESS_KEY=$$AWS_PRIVATE_KEY
					sudo eksctl create cluster \
					--name EKS-Cluster \
					--version 1.25 \
					--nodegroup-name standard-workers \
					--node-type t2.small \
					--nodes 2 \
					--nodes-min 1 \
					--nodes-max 3 \
					--node-ami auto \
					--region us-east-1 \
				'''
			}
		}

		

		stage('Create conf file cluster') {
			steps {
				sh '''
					export AWS_ACCESS_KEY_ID=$AWS_ACCES_KEY
					export AWS_SECRET_ACCESS_KEY=$$AWS_PRIVATE_KEY
					aws eks --region us-east-1 update-kubeconfig --name EKS-Cluster
				'''
			}
		}

	}
}
